;;; appkit-translate-test.el --- Translation boundaries -*- lexical-binding: t; -*-

(require 'ert)
(require 'appkit-test-helper)
(require 'appkit-translate)

(ert-deftest appkit-translate-replacement-revokes-old-result-not-other-source ()
  (appkit-test-with-surface
    (let* ((context (appkit-translate-context-create appkit-test-surface #'ignore))
           callbacks cancellations
           (backend (list :id 'one :label "One"
                          :start (lambda (source _language resolve _reject)
                                   (let ((text (plist-get source :text)))
                                     (push (cons text resolve) callbacks)
                                     (lambda () (push text cancellations))))))
           (old '(:key a :version "old" :text "Old text"))
           (new '(:key a :version "new" :text "New text"))
           (other '(:key b :version "b" :text "Other text")))
      (appkit-translate-request context old backend "zh")
      (appkit-translate-request context other backend "zh")
      (let ((obsolete (appkit-translate-state context old)))
        (appkit-translate-request context new backend "zh")
        (should (equal cancellations '("Old text")))
        (funcall (cdr (assoc "Old text" callbacks)) "Obsolete translation")
        (should-not (appkit-translate-state context old))
        (should (eq (plist-get (appkit-translate-state context new) :status) 'running))
        ;; A button from the old rendered region has lost its authority too.
        (appkit-translate--hide context obsolete)
        (should (plist-get (appkit-translate-state context new) :visible))
        (funcall (cdr (assoc "New text" callbacks)) "Current translation")
        (should (equal (plist-get (appkit-translate-state context new) :text) "Current translation"))
        (should (eq (plist-get (appkit-translate-state context other) :status) 'running))
        (appkit-translate--hide context (appkit-translate-state context other))
        (funcall (cdr (assoc "Other text" callbacks)) "Cancelled translation")
        (should (eq (plist-get (appkit-translate-state context other) :status) 'cancelled))
        (should (equal (plist-get (appkit-translate-state context new) :text) "Current translation"))))))

(ert-deftest appkit-translate-cache-is-bound-to-language-and-backend ()
  (appkit-test-with-surface
    (let* ((context (appkit-translate-context-create appkit-test-surface #'ignore))
           (source '(:key a :version 1 :text "Hello")) calls
           (start (lambda (_source language resolve _reject)
                    (push language calls)
                    (funcall resolve (concat "  " language "\n"))
                    nil))
           (first (list :id '(model one) :label "One" :start start))
           (second (list :id '(model two) :label "Two" :start start)))
      (appkit-translate-request context source first "zh")
      (let ((state (appkit-translate-state context source)))
        (appkit-translate--hide context state)
        (appkit-translate--again context state)
        (should (equal calls '("zh")))
        (should (equal (plist-get state :text) "  zh\n"))
        (should (plist-get state :visible)))
      (appkit-translate-request context source first "ja")
      (should (equal calls '("ja" "zh")))
      (appkit-translate-request context source second "ja")
      (should (equal calls '("ja" "ja" "zh")))
      (appkit-translate-request context source second "ja" t)
      (should (equal calls '("ja" "ja" "ja" "zh"))))))

(ert-deftest appkit-translate-queued-source-is-frozen-and-owner-close-revokes-it ()
  (appkit-test-with-surface
    (let* ((context (appkit-translate-context-create appkit-test-surface #'ignore))
           callbacks seen
           (backend (list :id 'one :label "One"
                          :start (lambda (source _language resolve _reject)
                                   (push (plist-get source :text) seen)
                                   (push resolve callbacks)
                                   nil)))
           (text (copy-sequence "Original"))
           (version (vector (copy-sequence "Version")))
           (source (list :key 'queued :version version :text text)))
      (appkit-translate-request context '(:key a :version 1 :text "First") backend "zh")
      (appkit-translate-request context '(:key b :version 1 :text "Second") backend "zh")
      (appkit-translate-request context source backend "zh")
      (should (eq (plist-get (appkit-translate-state context source) :status) 'queued))
      (aset text 0 ?X)
      (aset (aref version 0) 0 ?X)
      (funcall (cadr callbacks) "First completed")
      (should (equal (car seen) "Original"))
      (should-not (appkit-translate-state context source))
      (let ((state (appkit-translate-state context '(:key queued :version ["Version"])))
            (late (car callbacks)))
        (should (eq (plist-get state :status) 'running))
        (appkit-surface-stop appkit-test-surface)
        (funcall late "Late translation")
        (should-not (equal (plist-get state :text) "Late translation"))))))

(provide 'appkit-translate-test)
;;; appkit-translate-test.el ends here
